Traceback (most recent call last):
  File "/home/xinglong/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/xinglong/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Initialize HMMs, with inexact number of states
em_params, param_props = hmm.random_initialization(jr.PRNGKey(1))
sem_params, param_props = hmm.random_initialization(jr.PRNGKey(1))

# Fit
num_iters = 50

print('Fitting via exact EM...')
em_params, em_lps = hmm.fit_em(em_params, param_props, batch_emissions, num_iters)

print()
print('Fitting via stochastic EM (no progress bar)...')
minibatch_size = 3
emissions_generator = batch_emissions.reshape(num_batches // minibatch_size, minibatch_size, num_timesteps, emission_dim)
sem_params, sem_lps = hmm.fit_stochastic_em(sem_params, param_props, emissions_generator, num_epochs=num_iters)
print('\tDone')

# Plot log probs vs num_iterations
plt.plot(jnp.arange(len(em_lps)), em_lps, label='Exact EM')
plt.plot(jnp.arange(len(sem_lps)), sem_lps, label='Stochastic EM')
plt.xlabel('num epochs')
plt.ylabel('log prob')
plt.legend()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [4], line 9[0m
[1;32m      6[0m num_iters [38;5;241m=[39m [38;5;241m50[39m
[1;32m      8[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mFitting via exact EM...[39m[38;5;124m'[39m)
[0;32m----> 9[0m em_params, em_lps [38;5;241m=[39m [43mhmm[49m[38;5;241;43m.[39;49m[43mfit_em[49m[43m([49m[43mem_params[49m[43m,[49m[43m [49m[43mparam_props[49m[43m,[49m[43m [49m[43mbatch_emissions[49m[43m,[49m[43m [49m[43mnum_iters[49m[43m)[49m
[1;32m     11[0m [38;5;28mprint[39m()
[1;32m     12[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124mFitting via stochastic EM (no progress bar)...[39m[38;5;124m'[39m)

File [0;32m~/.local/lib/python3.10/site-packages/dynamax/abstractions.py:145[0m, in [0;36mSSM.fit_em[0;34m(self, initial_params, param_props, emissions, covariates, num_iters, verbose)[0m
[1;32m    143[0m [38;5;66;03m# Make sure the emissions and covariates have batch dimensions[39;00m
[1;32m    144[0m batch_emissions [38;5;241m=[39m ensure_array_has_batch_dim(emissions, [38;5;28mself[39m[38;5;241m.[39memission_shape)
[0;32m--> 145[0m batch_covariates [38;5;241m=[39m [43mensure_array_has_batch_dim[49m[43m([49m[43mcovariates[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcovariates_shape[49m[43m)[49m
[1;32m    147[0m [38;5;129m@jit[39m
[1;32m    148[0m [38;5;28;01mdef[39;00m [38;5;21mem_step[39m(params):
[1;32m    149[0m     batch_posteriors, lls [38;5;241m=[39m vmap(partial([38;5;28mself[39m[38;5;241m.[39me_step, params))(batch_emissions, batch_covariates)

File [0;32m~/.local/lib/python3.10/site-packages/dynamax/utils.py:137[0m, in [0;36mensure_array_has_batch_dim[0;34m(tree, instance_shapes)[0m
[1;32m    134[0m     [38;5;28;01melse[39;00m:
[1;32m    135[0m         [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124marray has too many dimensions![39m[38;5;124m"[39m)
[0;32m--> 137[0m [38;5;28;01mreturn[39;00m [43mtree_map[49m[43m([49m[43m_expand_dim[49m[43m,[49m[43m [49m[43mtree[49m[43m,[49m[43m [49m[43minstance_shapes[49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/jax/_src/tree_util.py:200[0m, in [0;36mtree_map[0;34m(f, tree, is_leaf, *rest)[0m
[1;32m    198[0m leaves, treedef [38;5;241m=[39m tree_flatten(tree, is_leaf)
[1;32m    199[0m all_leaves [38;5;241m=[39m [leaves] [38;5;241m+[39m [treedef[38;5;241m.[39mflatten_up_to(r) [38;5;28;01mfor[39;00m r [38;5;129;01min[39;00m rest]
[0;32m--> 200[0m [38;5;28;01mreturn[39;00m [43mtreedef[49m[38;5;241;43m.[39;49m[43munflatten[49m[43m([49m[43mf[49m[43m([49m[38;5;241;43m*[39;49m[43mxs[49m[43m)[49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mxs[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[38;5;28;43mzip[39;49m[43m([49m[38;5;241;43m*[39;49m[43mall_leaves[49m[43m)[49m[43m)[49m

File [0;32m~/.local/lib/python3.10/site-packages/jax/_src/tree_util.py:200[0m, in [0;36m<genexpr>[0;34m(.0)[0m
[1;32m    198[0m leaves, treedef [38;5;241m=[39m tree_flatten(tree, is_leaf)
[1;32m    199[0m all_leaves [38;5;241m=[39m [leaves] [38;5;241m+[39m [treedef[38;5;241m.[39mflatten_up_to(r) [38;5;28;01mfor[39;00m r [38;5;129;01min[39;00m rest]
[0;32m--> 200[0m [38;5;28;01mreturn[39;00m treedef[38;5;241m.[39munflatten([43mf[49m[43m([49m[38;5;241;43m*[39;49m[43mxs[49m[43m)[49m [38;5;28;01mfor[39;00m xs [38;5;129;01min[39;00m [38;5;28mzip[39m([38;5;241m*[39mall_leaves))

File [0;32m~/.local/lib/python3.10/site-packages/dynamax/utils.py:123[0m, in [0;36mensure_array_has_batch_dim.<locals>._expand_dim[0;34m(x, shp)[0m
[1;32m    122[0m [38;5;28;01mdef[39;00m [38;5;21m_expand_dim[39m(x, shp):
[0;32m--> 123[0m     ndim [38;5;241m=[39m [38;5;28;43mlen[39;49m[43m([49m[43mshp[49m[43m)[49m
[1;32m    124[0m     [38;5;28;01massert[39;00m x[38;5;241m.[39mndim [38;5;241m>[39m ndim, [38;5;124m"[39m[38;5;124marray does not match expected shape![39m[38;5;124m"[39m
[1;32m    125[0m     [38;5;28;01massert[39;00m [38;5;28mall[39m([(d1 [38;5;241m==[39m d2) [38;5;28;01mfor[39;00m d1, d2 [38;5;129;01min[39;00m [38;5;28mzip[39m(x[38;5;241m.[39mshape[[38;5;241m-[39mndim:], shp)]), \
[1;32m    126[0m         [38;5;124m"[39m[38;5;124marray does not match expected shape![39m[38;5;124m"[39m

[0;31mTypeError[0m: object of type 'NoneType' has no len()
TypeError: object of type 'NoneType' has no len()

